export const LOGIN = "LOGIN";
export const LOGOUT = "LOGOUT";

export const FETCH_TESTS = "FETCH_TESTS";
export const FETCH_TEST = "FETCH_TEST";
export const CREATE_TEST = "CREATE_TEST";
export const DELETE_TEST = "DELETE_TEST";
export const EDIT_TEST = "EDIT_TEST";

export const VISIBLE_TEST_YES = "VISIBLE_YES";
export const VISIBLE_TEST_NO = "VISIBLE_NO";
export const VISIBLE_SECTION_YES = "VISIBLE_SECTION_YES";
export const VISIBLE_SECTION_NO = "VISIBLE_SECTION_NO";
export const VISIBLE_DELETE_TEST_YES = "VISIBLE_DELETE_TEST_YES";
export const VISIBLE_DELETE_TEST_NO = "VISIBLE_DELETE_TEST_NO";
export const VISIBLE_DELETE_SECTION_YES = "VISIBLE_DELETE_SECTION_YES";
export const VISIBLE_DELETE_SECTION_NO = "VISIBLE_DELETE_SECTION_NO";

export const SELECTED_SECTION_ID = "SELECTED_SECTION_ID";
export const SELECTED_QUESTION = "SELECTED_QUESTION";
export const SELECTED_SECTION_NO = "SELECTED_SECTION_NO";

export const FETCH_QUESTIONS = "FETCH_SECTIONS";
export const EDIT_QUESTION = "EDIT_QUESTION";
export const DELETE_QUESTION = "DELETE_QUESTION";
export const EMPTY_QUESTIONS = "EMPTY_QUESTIONS";

export const FETCH_ANSWERS = "FETCH_ANSWERS";
export const EDIT_ANSWER = "EDIT_ANSWER";
export const EMPTY_ANSWERS = "EMPTY_ANSWERS";

export const EXAM_ID = "EXAM_ID";
export const CREATE_EXAM = "CREATE_EXAM";
export const DELETE_EXAM = "DELETE_EXAM";
